export const profiles = [
  {
    platform: "LeetCode",
    username: "XoXoHarsh",
    stats: [
      { label: "Max Rating", value: "1,962" },
      { label: "Problems Solved", value: "690+" },
      { label: "Level", value: "Knight" },
      { label: "Contests", value: "35+" },
    ],
    link: "https://leetcode.com/XoXoHarsh/",
    gradient: "from-yellow-500 to-yellow-600",
    bgGradient: "from-yellow-500/20 to-yellow-600/20",
  },
  {
    platform: "GitHub",
    username: "HarshSharma20503",
    stats: [
      { label: "Contributions", value: "1,300+" },
      { label: "Repositories", value: "51" },
      { label: "Profile Views", value: "4,000+" },
      { label: "Followers", value: "29" },
    ],
    link: "https://github.com/XoXoHarsh",
    gradient: "from-purple-500 to-purple-600",
    bgGradient: "from-purple-500/20 to-purple-600/20",
  },
  {
    platform: "CodeForces",
    username: "XoXoHarsh",
    stats: [
      { label: "Max Rating", value: "1,556" },
      { label: "Max Rank", value: "Specialist" },
      { label: "Problems Solved", value: "550+" },
      { label: "Contests", value: "90+" },
    ],
    link: "https://codeforces.com/profile/XoXoHarsh",
    gradient: "from-red-500 to-red-600",
    bgGradient: "from-red-500/20 to-red-600/20",
  },
  {
    platform: "GeeksforGeeks",
    username: "harshsharma20503",
    stats: [
      { label: "Problems Solved", value: "250+" },
      { label: "Streak", value: "32" },
      { label: "Coding Score", value: "768" },
    ],
    link: "https://auth.geeksforgeeks.org/user/harshsharma20503",
    gradient: "from-green-500 to-green-600",
    bgGradient: "from-green-500/20 to-green-600/20",
  },
  {
    platform: "HackerRank",
    username: "harshsharma20503",
    stats: [
      { label: "Problem Solving", value: "6 ⭐" },
      { label: "C++", value: "5 ⭐" },
      { label: "Badges", value: "6" },
      { label: "Certificates", value: "2" },
    ],
    link: "https://www.hackerrank.com/harshsharma20503",
    gradient: "from-emerald-500 to-emerald-600",
    bgGradient: "from-emerald-500/20 to-emerald-600/20",
  },
  {
    platform: "CodeChef",
    username: "xoharshxo",
    stats: [
      { label: "Max Rating", value: "1872" },
      { label: "Level", value: "4 ⭐" },
      { label: "Best Contest Rank", value: "91" },
    ],
    link: "https://www.codechef.com/users/xoharshxo",
    gradient: "from-orange-500 to-orange-600",
    bgGradient: "from-orange-500/20 to-orange-600/20",
  },
];
